dist: trusty

language: node_js

node_js:
  - "6"
  - "8"

# Use container-based Travis infrastructure.
sudo: false

branches:
  only:
    - master
    - next

notifications:
  email:
    on_success: change
    on_failure: always

cache: yarn

script:
  # Run tests
  - yarn run type-check
  - yarn run lint
  - yarn run test
  - yarn run coverage
  # Upload to coveralls, but don't _fail_ if coveralls is down.
  - cat coverage/lcov.info | node_modules/.bin/coveralls || echo "Coveralls upload failed"
  # Build and check bundlesize
  - yarn run build-bundles
  - yarn run bundlesize
